### ISSUE TITLE
Feature : Database-agnostic ?

### ISSUE THREAD

**Issue by vlordier** [synw/django-rechat#1]
Rework history management to use any JSON database (Postgres, Mongo, CouchDB, whatever comes up) to provide easier maintainability as DBs come and go, and flexibility for architectural choices.

**Comment by synw** [comment]
Good idea. This module still needs a bit of work, so it could be an occasion to make it database agnostic yes.

**Comment by synw** [comment]
I refactored and updated the code for the latest [django-instant](https://github.com/synw/django-instant) version. It is now database agnostic. For this i used events and hooks from [django-mqueue](https://github.com/synw/django-mqueue)

It is very easy to create new hooks to save to whatever database : check [the doc](http://django-rechat.readthedocs.io/en/latest/src/history.html).

I plan to add presence, refine authorizations and probably introduce rooms, then maybe grow up this project out of its actual pet project condition. If it becomes a serious module I would use a little help for the frontend, if anyone is interested.
